In [10]:
import sys

print(sys.executable)

c:\Users\Lenovo\Documents\HDB_ETL\venv\Scripts\python.exe

In [11]:
import pandas as pd

print(pd.__version__)

2.3.3

In [12]:
import sys

sys.path.append("../src")

from extract import extract_data

print("Extract module loaded")

Extract module loaded

In [13]:
import sys

sys.path.append("../src")

from extract import extract_data

In [14]:
RAW_PATH = "../data/raw"

In [15]:
master_df = extract_data(
    RAW_PATH
)

Reading file: ../data/raw\master_dataset.csv

c:\Users\Lenovo\Documents\HDB_ETL\notebooks\../src\extract.py:27: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Reading file: ../data/raw\Resale Flat Prices (Based on Approval Date), 1990 - 1999.csv
Reading file: ../data/raw\Resale Flat Prices (Based on Approval Date), 2000 - Feb 2012.csv
Reading file: ../data/raw\Resale Flat Prices (Based on Registration Date), From Jan 2015 to Dec 2016.csv
Reading file: ../data/raw\Resale Flat Prices (Based on Registration Date), From Mar 2012 to Dec 2014.csv
Reading file: ../data/raw\Resale flat prices based on registration date from Jan-2017 onwards.csv

In [16]:
master_df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,source_file,remaining_lease
0,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,9000.0,master_dataset.csv,NaN
1,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,04 TO 06,31.0,IMPROVED,1977,6000.0,master_dataset.csv,NaN
2,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,8000.0,master_dataset.csv,NaN
3,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,07 TO 09,31.0,IMPROVED,1977,6000.0,master_dataset.csv,NaN
4,1990-01,ANG MO KIO,3 ROOM,216,ANG MO KIO AVE 1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,master_dataset.csv,NaN

In [17]:
master_df.shape

(1964022, 12)

In [18]:
master_df.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price',
       'source_file', 'remaining_lease'],
      dtype='object')

In [19]:
master_df.to_csv(
    "../data/raw/master_dataset.csv",
    index=False
)

In [20]:
from profiling import profile_dataset

In [21]:
profile = profile_dataset(
    master_df
)

In [22]:
profile

{'row_count': 1964022,
 'column_count': 12,
 'columns': ['month',
  'town',
  'flat_type',
  'block',
  'street_name',
  'storey_range',
  'floor_area_sqm',
  'flat_model',
  'lease_commence_date',
  'resale_price',
  'source_file',
  'remaining_lease'],
 'data_types': {'month': 'object',
  'town': 'object',
  'flat_type': 'object',
  'block': 'object',
  'street_name': 'object',
  'storey_range': 'object',
  'floor_area_sqm': 'float64',
  'flat_model': 'object',
  'lease_commence_date': 'int64',
  'resale_price': 'float64',
  'source_file': 'object',
  'remaining_lease': 'object'},
 'missing_values': {'remaining_lease': 1418100,
  'month': 0,
  'town': 0,
  'flat_type': 0,
  'block': 0,
  'street_name': 0,
  'storey_range': 0,
  'floor_area_sqm': 0,
  'flat_model': 0,
  'lease_commence_date': 0,
  'resale_price': 0,
  'source_file': 0},
 'unique_count': {'month': 439,
  'town': 27,
  'flat_type': 8,
  'block': 2772,
  'street_name': 595,
  'storey_range': 25,
  'floor_area_sqm': 232,
  'flat_model': 34,
  'lease_commence_date': 57,
  'resale_price': 10274,
  'source_file': 6,
  'remaining_lease': 750},
 'duplicate_records': np.int64(3854),
 'statistics': {'floor_area_sqm': {'count': 1964022.0,
   'mean': 95.66031164620357,
   'std': 25.72325787749771,
   'min': 28.0,
   '25%': 73.0,
   '50%': 93.0,
   '75%': 113.0,
   'max': 366.7},
  'lease_commence_date': {'count': 1964022.0,
   'mean': 1988.8420832353202,
   'std': 11.215022395707258,
   'min': 1966.0,
   '25%': 1981.0,
   '50%': 1986.0,
   '75%': 1996.0,
   'max': 2022.0},
  'resale_price': {'count': 1964022.0,
   'mean': 338964.9800116394,
   'std': 188005.96033232397,
   'min': 5000.0,
   '25%': 200000.0,
   '50%': 310000.0,
   '75%': 438500.0,
   'max': 1728000.0}}}

In [23]:
from ydata_profiling import ProfileReport

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13896\44057814.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [24]:
report = ProfileReport(
    master_df,
    title="HDB Resale Data Profiling"
)

report.to_file(
    "../reports/profile_report.html"
)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:25<00:00,  2.12s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [25]:
print(sys.executable)

c:\Users\Lenovo\Documents\HDB_ETL\venv\Scripts\python.exe

In [26]:
master_df.shape

(1964022, 12)

In [27]:
master_df.columns.tolist()

['month',
 'town',
 'flat_type',
 'block',
 'street_name',
 'storey_range',
 'floor_area_sqm',
 'flat_model',
 'lease_commence_date',
 'resale_price',
 'source_file',
 'remaining_lease']

In [28]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1964022 entries, 0 to 1964021
Data columns (total 12 columns):
 #   Column               Dtype
---  ------               -----
 0   month                object
 1   town                 object
 2   flat_type            object
 3   block                object
 4   street_name          object
 5   storey_range         object
 6   floor_area_sqm       float64
 7   flat_model           object
 8   lease_commence_date  int64
 9   resale_price         float64
 10  source_file          object
 11  remaining_lease      object
dtypes: float64(2), int64(1), object(9)
memory usage: 179.8+ MB

In [29]:
master_df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,source_file,remaining_lease
0,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,9000.0,master_dataset.csv,NaN
1,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,04 TO 06,31.0,IMPROVED,1977,6000.0,master_dataset.csv,NaN
2,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,8000.0,master_dataset.csv,NaN
3,1990-01,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,07 TO 09,31.0,IMPROVED,1977,6000.0,master_dataset.csv,NaN
4,1990-01,ANG MO KIO,3 ROOM,216,ANG MO KIO AVE 1,04 TO 06,73.0,NEW GENERATION,1976,47200.0,master_dataset.csv,NaN

In [30]:
master_df.duplicated().sum()

np.int64(3854)

In [31]:
master_df.to_csv(
    "../data/raw/master_dataset.csv",
    index=False
)

In [32]:
from profiling import profile_dataset

In [33]:
profile = profile_dataset(
    master_df
)

In [34]:
profile.keys()

dict_keys(['row_count', 'column_count', 'columns', 'data_types', 'missing_values', 'unique_count', 'duplicate_records', 'statistics'])

In [35]:
import json


with open(
    "../reports/data_profile.json",
    "w"
) as file:

    json.dump(
        profile,
        file,
        indent=4,
        default=str
    )

In [36]:
from ydata_profiling import ProfileReport


report = ProfileReport(
    master_df,
    title="HDB Resale Data Profile"
)


report.to_file(
    "../reports/hdb_profile.html"
)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:54<00:00,  4.56s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [37]:
master_df.columns.tolist()

['month',
 'town',
 'flat_type',
 'block',
 'street_name',
 'storey_range',
 'floor_area_sqm',
 'flat_model',
 'lease_commence_date',
 'resale_price',
 'source_file',
 'remaining_lease']

In [38]:
from profiling import profile_dataset

In [39]:
profile = profile_dataset(master_df)

In [40]:
profile

{'row_count': 1964022,
 'column_count': 12,
 'columns': ['month',
  'town',
  'flat_type',
  'block',
  'street_name',
  'storey_range',
  'floor_area_sqm',
  'flat_model',
  'lease_commence_date',
  'resale_price',
  'source_file',
  'remaining_lease'],
 'data_types': {'month': 'object',
  'town': 'object',
  'flat_type': 'object',
  'block': 'object',
  'street_name': 'object',
  'storey_range': 'object',
  'floor_area_sqm': 'float64',
  'flat_model': 'object',
  'lease_commence_date': 'int64',
  'resale_price': 'float64',
  'source_file': 'object',
  'remaining_lease': 'object'},
 'missing_values': {'remaining_lease': 1418100,
  'month': 0,
  'town': 0,
  'flat_type': 0,
  'block': 0,
  'street_name': 0,
  'storey_range': 0,
  'floor_area_sqm': 0,
  'flat_model': 0,
  'lease_commence_date': 0,
  'resale_price': 0,
  'source_file': 0},
 'unique_count': {'month': 439,
  'town': 27,
  'flat_type': 8,
  'block': 2772,
  'street_name': 595,
  'storey_range': 25,
  'floor_area_sqm': 232,
  'flat_model': 34,
  'lease_commence_date': 57,
  'resale_price': 10274,
  'source_file': 6,
  'remaining_lease': 750},
 'duplicate_records': np.int64(3854),
 'statistics': {'floor_area_sqm': {'count': 1964022.0,
   'mean': 95.66031164620357,
   'std': 25.72325787749771,
   'min': 28.0,
   '25%': 73.0,
   '50%': 93.0,
   '75%': 113.0,
   'max': 366.7},
  'lease_commence_date': {'count': 1964022.0,
   'mean': 1988.8420832353202,
   'std': 11.215022395707258,
   'min': 1966.0,
   '25%': 1981.0,
   '50%': 1986.0,
   '75%': 1996.0,
   'max': 2022.0},
  'resale_price': {'count': 1964022.0,
   'mean': 338964.9800116394,
   'std': 188005.96033232397,
   'min': 5000.0,
   '25%': 200000.0,
   '50%': 310000.0,
   '75%': 438500.0,
   'max': 1728000.0}}}

In [41]:
import json


with open(
    "../reports/profile_report.json",
    "w"
) as f:

    json.dump(
        profile,
        f,
        indent=4,
        default=str
    )

In [42]:
from ydata_profiling import ProfileReport


profile_report = ProfileReport(
    master_df,
    title="HDB Resale Dataset Profiling",
    minimal=True
)


profile_report.to_file(
    "../reports/hdb_profile.html"
)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:08<00:00,  1.40it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [43]:
master_df.isnull().sum()

month                        0
town                         0
flat_type                    0
block                        0
street_name                  0
storey_range                 0
floor_area_sqm               0
flat_model                   0
lease_commence_date          0
resale_price                 0
source_file                  0
remaining_lease        1418100
dtype: int64

In [44]:
master_df = master_df.drop(
    columns=["remaining_lease"]
)

In [45]:
master_df.columns.tolist()

['month',
 'town',
 'flat_type',
 'block',
 'street_name',
 'storey_range',
 'floor_area_sqm',
 'flat_model',
 'lease_commence_date',
 'resale_price',
 'source_file']

In [46]:
master_df.isnull().sum()

month                  0
town                   0
flat_type              0
block                  0
street_name            0
storey_range           0
floor_area_sqm         0
flat_model             0
lease_commence_date    0
resale_price           0
source_file            0
dtype: int64

In [47]:
import pandas as pd
from datetime import datetime
from dateutil.relativedelta import relativedelta

In [48]:
from datetime import datetime


CURRENT_DATE = datetime.today()

In [49]:
CURRENT_DATE = datetime.today()

print(CURRENT_DATE)

2026-07-20 00:20:55.976351

In [50]:
from datetime import datetime
from dateutil.relativedelta import relativedelta


def calculate_remaining_lease(lease_year):

    CURRENT_DATE = datetime.today()


    # Create lease start date
    lease_start_date = datetime(
        int(lease_year),
        1,
        1
    )


    # HDB lease is 99 years
    lease_end_date = (
        lease_start_date
        + relativedelta(years=99)
    )


    # Calculate difference
    remaining = relativedelta(
        lease_end_date,
        CURRENT_DATE
    )


    # Handle expired lease
    if remaining.years < 0:
        return "0 years 0 months"


    return (
        f"{remaining.years} years "
        f"{remaining.months} months"
    )

In [51]:
calculate_remaining_lease(1985)

'57 years 5 months'

In [52]:
master_df["lease_commence_date"]

0          1977
1          1977
2          1977
3          1977
4          1976
           ...
1964017    1987
1964018    1988
1964019    1987
1964020    1987
1964021    1988
Name: lease_commence_date, Length: 1964022, dtype: int64

In [53]:
master_df["remaining_lease"] = (
    master_df["lease_commence_date"]
    .apply(calculate_remaining_lease)
)

In [54]:
master_df[
    [
        "lease_commence_date",
        "remaining_lease"
    ]
].head(10)

   lease_commence_date    remaining_lease
0                 1977  49 years 5 months
1                 1977  49 years 5 months
2                 1977  49 years 5 months
3                 1977  49 years 5 months
4                 1976  48 years 5 months
5                 1977  49 years 5 months
6                 1977  49 years 5 months
7                 1977  49 years 5 months
8                 1977  49 years 5 months
9                 1977  49 years 5 months

In [55]:
master_df.to_csv(
    "../data/cleaned/cleaned_dataset.csv",
    index=False
)

In [56]:
master_df["town"].value_counts()

town
TAMPINES           168260
YISHUN             147346
JURONG WEST        140422
WOODLANDS          139048
BEDOK              138580
ANG MO KIO         108368
HOUGANG            107070
BUKIT BATOK         95026
CHOA CHU KANG       81324
SENGKANG            73244
BUKIT MERAH         72836
PASIR RIS           69314
TOA PAYOH           67216
QUEENSTOWN          60454
GEYLANG             59232
BUKIT PANJANG       58884
CLEMENTI            58386
KALLANG/WHAMPOA     57886
JURONG EAST         51708
PUNGGOL             48550
SERANGOON           47344
BISHAN              44186
SEMBAWANG           32186
MARINE PARADE       16710
CENTRAL AREA        15038
BUKIT TIMAH          5276
LIM CHU KANG          128
Name: count, dtype: int64

In [57]:
master_df["flat_type"].value_counts()

flat_type
4 ROOM              752346
3 ROOM              618568
5 ROOM              416268
EXECUTIVE           145998
2 ROOM               27090
1 ROOM                2646
MULTI GENERATION       558
MULTI-GENERATION       548
Name: count, dtype: int64

In [58]:
VALID_TOWNS = [
'TAMPINES',
'YISHUN',
'JURONG WEST',
'WOODLANDS',
'BEDOK',
'ANG MO KIO',
'HOUGANG',
'BUKIT BATOK',
'CHOA CHU KANG',
'SENGKANG',
'BUKIT MERAH',
'PASIR RIS',
'TOA PAYOH',
'QUEENSTOWN',
'GEYLANG',
'BUKIT PANJANG',
'CLEMENTI',
'KALLANG/WHAMPOA',
'JURONG EAST',
'PUNGGOL',
'SERANGOON',
'BISHAN',
'SEMBAWANG',
'MARINE PARADE',
'CENTRAL AREA',
'BUKIT TIMAH',
'LIM CHU KANG'
]

In [59]:
master_df["flat_model"].value_counts()

flat_model
Model A                   433128
Improved                  362488
New Generation            232586
NEW GENERATION            157796
IMPROVED                  147178
MODEL A                   140762
Premium Apartment         104398
Simplified                 72704
Apartment                  54534
Standard                   52980
SIMPLIFIED                 46516
Maisonette                 37476
STANDARD                   34750
MAISONETTE                 24430
Model A2                   21438
APARTMENT                  19802
DBSS                        8072
Adjoined flat               2662
Model A-Maisonette          2360
MODEL A-MAISONETTE          1964
Type S1                     1044
2-room                       968
Terrace                      940
MULTI GENERATION             558
Multi Generation             548
Type S2                      500
TERRACE                      494
Premium Apartment Loft       288
Premium Maisonette           188
Improved-Maisonette          174
3Gen                         154
IMPROVED-MAISONETTE           88
2-ROOM                        42
PREMIUM APARTMENT             12
Name: count, dtype: int64

In [60]:
from cleaning import standardize_flat_model

In [61]:
clean_df = standardize_flat_model(
    master_df
)

In [62]:
clean_df["flat_model"].value_counts()

flat_model
MODEL A                   573890
IMPROVED                  509666
NEW GENERATION            390382
SIMPLIFIED                119220
PREMIUM APARTMENT         104410
STANDARD                   87730
APARTMENT                  74336
MAISONETTE                 61906
MODEL A2                   21438
DBSS                        8072
MODEL A-MAISONETTE          4324
ADJOINED FLAT               2662
TERRACE                     1434
MULTI-GENERATION            1106
TYPE S1                     1044
2 ROOM                      1010
TYPE S2                      500
PREMIUM APARTMENT LOFT       288
IMPROVED-MAISONETTE          262
PREMIUM MAISONETTE           188
3GEN                         154
Name: count, dtype: int64

In [63]:
master_df["storey_range"].value_counts().head(20)

storey_range
04 TO 06    490154
07 TO 09    443080
01 TO 03    391932
10 TO 12    378272
13 TO 15    134900
16 TO 18     53404
19 TO 21     25100
22 TO 24     16348
25 TO 27      7884
01 TO 05      5400
06 TO 10      4948
28 TO 30      3962
11 TO 15      2518
31 TO 33      1652
34 TO 36      1482
37 TO 39      1244
40 TO 42       604
16 TO 20       530
21 TO 25       184
43 TO 45       166
Name: count, dtype: int64

In [64]:
import sys

sys.path.append("../src")

In [65]:
from validation import validate_dataset

In [66]:
import importlib
import validation

importlib.reload(validation)

from validation import validate_dataset

In [67]:
master_df.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price',
       'source_file', 'remaining_lease'],
      dtype='object')

In [68]:
clean_df, failed_df = validate_dataset(
    master_df
)

In [70]:
import pandas as pd
from datetime import datetime


def standardize_flat_model(df):

    ...
    return df


def remove_duplicates(df):

    ...
    return clean_df, duplicate_df


def calculate_remaining_lease(df):

    ...
    return df


def detect_price_anomalies(df):

    ...
    return df, anomaly_df

In [71]:
clean_df = standardize_flat_model(clean_df)

In [74]:
import importlib
import cleaning

importlib.reload(cleaning)

from cleaning import (
    standardize_flat_model,
    remove_duplicates,
    calculate_remaining_lease,
    detect_price_anomalies
)

In [75]:
clean_df = standardize_flat_model(clean_df)

clean_df, duplicate_df = remove_duplicates(clean_df)

clean_df = calculate_remaining_lease(clean_df)

clean_df, anomaly_df = detect_price_anomalies(clean_df)

In [76]:
print(clean_df.shape)
print(duplicate_df.shape)
print(anomaly_df.shape)

clean_df.head()

(1901832, 13)
(62190, 13)
(49776, 14)

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,source_file,remaining_lease,is_price_anomaly
970929,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,master_dataset.csv,91 years 6 months,True
1952940,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,Resale flat prices based on registration date ...,91 years 6 months,True
1958780,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,Resale flat prices based on registration date ...,88 years 6 months,True
976769,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,master_dataset.csv,88 years 6 months,True
958277,2025-06,QUEENSTOWN,5 ROOM,92,DAWSON RD,22 TO 24,122.0,PREMIUM APARTMENT LOFT,2016,1658888.0,master_dataset.csv,88 years 6 months,True

In [77]:
import importlib
import cleaning

importlib.reload(cleaning)

from cleaning import (
    standardize_flat_model,
    remove_duplicates,
    calculate_remaining_lease,
    detect_price_anomalies
)

clean_df = standardize_flat_model(clean_df)

clean_df, duplicate_df = remove_duplicates(clean_df)

clean_df = calculate_remaining_lease(clean_df)

clean_df, anomaly_df = detect_price_anomalies(clean_df)

In [78]:
print(clean_df.shape)
print(duplicate_df.shape)
print(anomaly_df.shape)

clean_df.head()

(1901832, 13)
(0, 14)
(49776, 14)

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,source_file,remaining_lease,is_price_anomaly
970929,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,master_dataset.csv,91 years 6 months,True
1952940,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,Resale flat prices based on registration date ...,91 years 6 months,True
1958780,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,Resale flat prices based on registration date ...,88 years 6 months,True
976769,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,master_dataset.csv,88 years 6 months,True
958277,2025-06,QUEENSTOWN,5 ROOM,92,DAWSON RD,22 TO 24,122.0,PREMIUM APARTMENT LOFT,2016,1658888.0,master_dataset.csv,88 years 6 months,True

In [79]:
avg_price = (
    clean_df.groupby(
        ["month", "town", "flat_type"]
    )["resale_price"]
    .mean()
    .reset_index(name="avg_price")
)

In [80]:
clean_df = clean_df.merge(
    avg_price,
    on=["month", "town", "flat_type"],
    how="left"
)

In [88]:
avg_price = (
    clean_df.groupby(
        ["month", "town", "flat_type"]
    )["resale_price"]
    .mean()
    .reset_index(name="avg_price")
)

print(avg_price.head())
print(avg_price.columns)

     month        town flat_type      avg_price
0  1990-01  ANG MO KIO    1 ROOM    7000.000000
1  1990-01  ANG MO KIO    3 ROOM   44871.578947
2  1990-01  ANG MO KIO    4 ROOM   74218.750000
3  1990-01  ANG MO KIO    5 ROOM  138392.857143
4  1990-01       BEDOK    2 ROOM   24500.000000
Index(['month', 'town', 'flat_type', 'avg_price'], dtype='object')

In [89]:
temp_df = clean_df.merge(
    avg_price,
    on=["month", "town", "flat_type"],
    how="left"
)

print(temp_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price_x', 'Resale Identifier', 'avg_price_y']

In [90]:
print(clean_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier']

In [91]:
if "avg_price" in df.columns:
    df = df.drop(columns=["avg_price"])

NameError: name 'df' is not defined

In [81]:
import re

def create_resale_identifier(row):

    block_digits = re.sub(r"\D", "", str(row["block"]))

    block_digits = block_digits[:3].zfill(3)

    avg_digits = str(int(row["avg_price"]))[:2]

    month = row["month"][-2:]

    town_initial = row["town"][0]

    return f"S{block_digits}{avg_digits}{month}{town_initial}"

In [82]:
clean_df["Resale Identifier"] = clean_df.apply(
    create_resale_identifier,
    axis=1
)

In [83]:
clean_df[
    ["block",
     "month",
     "town",
     "flat_type",
     "avg_price",
     "Resale Identifier"]
].head()

  block    month         town flat_type     avg_price Resale Identifier
0   96A  2026-04  BUKIT MERAH    5 ROOM  1.055782e+06         S0961004B
1   96A  2026-04  BUKIT MERAH    5 ROOM  1.055782e+06         S0961004B
2    92  2026-02   QUEENSTOWN    5 ROOM  1.180167e+06         S0921102Q
3    92  2026-02   QUEENSTOWN    5 ROOM  1.180167e+06         S0921102Q
4    92  2025-06   QUEENSTOWN    5 ROOM  1.232815e+06         S0921206Q

In [84]:
import hashlib

def hash_identifier(df):

    df = df.copy()

    df["Hashed Identifier"] = (
        df["Resale Identifier"]
        .apply(
            lambda x: hashlib.sha256(
                x.encode("utf-8")
            ).hexdigest()
        )
    )

    return df

In [116]:
import importlib
import transformation

importlib.reload(transformation)

from transformation import create_resale_identifier

In [117]:
transformed_df = create_resale_identifier(clean_df)

In [101]:
print(clean_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier']

In [102]:
transformed_df = clean_df.copy()

In [103]:
import importlib
import hashing

importlib.reload(hashing)

from hashing import hash_identifier

hashed_df = hash_identifier(transformed_df)

hashed_df[
    ["Resale Identifier", "Hashed Identifier"]
].head()

  Resale Identifier                                  Hashed Identifier
0         S0961004B  acf02627fe56dc5b7fb5dd8656b2165840840e43fcfa6d...
1         S0961004B  acf02627fe56dc5b7fb5dd8656b2165840840e43fcfa6d...
2         S0921102Q  fe8c51e42b8e500e229d8b880a01c0db4aff1fe768a8fe...
3         S0921102Q  fe8c51e42b8e500e229d8b880a01c0db4aff1fe768a8fe...
4         S0921206Q  b402eb5dc0d00f534459113590b8eb519ad7aba78a6d64...

In [104]:
import importlib
import output

importlib.reload(output)

from output import save_outputs

In [105]:
save_outputs(
    master_df,
    clean_df,
    transformed_df,
    hashed_df,
    failed_df,
    duplicate_df,
    anomaly_df
)

All output files generated successfully.

In [106]:
print("Raw Records:", len(master_df))
print("Clean Records:", len(clean_df))
print("Validation Failures:", len(failed_df))
print("Duplicate Records:", len(duplicate_df))
print("Price Anomalies:", len(anomaly_df))

Raw Records: 1964022
Clean Records: 1901832
Validation Failures: 0
Duplicate Records: 0
Price Anomalies: 49776

In [107]:
hashed_df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,source_file,remaining_lease,is_price_anomaly,avg_price,Resale Identifier,Hashed Identifier
0,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,master_dataset.csv,91 years 6 months,True,1.055782e+06,S0961004B,acf02627fe56dc5b7fb5dd8656b2165840840e43fcfa6d...
1,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,Resale flat prices based on registration date ...,91 years 6 months,True,1.055782e+06,S0961004B,acf02627fe56dc5b7fb5dd8656b2165840840e43fcfa6d...
2,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,Resale flat prices based on registration date ...,88 years 6 months,True,1.180167e+06,S0921102Q,fe8c51e42b8e500e229d8b880a01c0db4aff1fe768a8fe...
3,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,master_dataset.csv,88 years 6 months,True,1.180167e+06,S0921102Q,fe8c51e42b8e500e229d8b880a01c0db4aff1fe768a8fe...
4,2025-06,QUEENSTOWN,5 ROOM,92,DAWSON RD,22 TO 24,122.0,PREMIUM APARTMENT LOFT,2016,1658888.0,master_dataset.csv,88 years 6 months,True,1.232815e+06,S0921206Q,b402eb5dc0d00f534459113590b8eb519ad7aba78a6d64...

In [108]:
print("Clean DF Columns")
print(clean_df.columns.tolist())

print("\nTransformed DF Columns")
print(transformed_df.columns.tolist())

print("\nHashed DF Columns")
print(hashed_df.columns.tolist())

Clean DF Columns
['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier']

Transformed DF Columns
['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier']

Hashed DF Columns
['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier', 'Hashed Identifier']

In [109]:
clean_df = clean_df.drop(
    columns=[
        "avg_price",
        "Resale Identifier"
    ],
    errors="ignore"
)

In [110]:
print(clean_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly']

In [111]:
print(transformed_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier']

In [112]:
print(hashed_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier', 'Hashed Identifier']

In [113]:
save_outputs(
    master_df,
    clean_df,
    transformed_df,
    hashed_df,
    failed_df,
    duplicate_df,
    anomaly_df
)

All output files generated successfully.

In [118]:
print(transformed_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier']

In [119]:
clean_df = calculate_remaining_lease(clean_df)

transformed_df = create_resale_identifier(clean_df)

hashed_df = hash_identifier(transformed_df)

In [120]:
print(hashed_df.columns.tolist())

['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'resale_price', 'source_file', 'remaining_lease', 'is_price_anomaly', 'avg_price', 'Resale Identifier', 'Hashed Identifier']

In [121]:
import importlib
import output

importlib.reload(output)

from output import save_outputs

In [122]:
save_outputs(
    master_df,
    clean_df,
    transformed_df,
    hashed_df,
    failed_df,
    duplicate_df,
    anomaly_df
)

Output files generated successfully.

In [123]:
print("Raw:", len(master_df))
print("Clean:", len(clean_df))
print("Transformed:", len(transformed_df))
print("Hashed:", len(hashed_df))
print("Validation Failed:", len(failed_df))
print("Duplicates:", len(duplicate_df))
print("Anomalies:", len(anomaly_df))

Raw: 1964022
Clean: 1901832
Transformed: 1901832
Hashed: 1901832
Validation Failed: 0
Duplicates: 0
Anomalies: 49776

In [124]:
print(
    hashed_df["Resale Identifier"].nunique()
)

print(
    hashed_df["Hashed Identifier"].nunique()
)

650218
650218

In [125]:
failed_df.head()

duplicate_df.head()

anomaly_df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,source_file,remaining_lease,is_price_anomaly,failed_reason
970929,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,master_dataset.csv,91 years 6 months,True,Potential resale price anomaly
1952940,2026-04,BUKIT MERAH,5 ROOM,96A,HENDERSON RD,46 TO 48,113.0,IMPROVED,2019,1728000.0,Resale flat prices based on registration date ...,91 years 6 months,True,Potential resale price anomaly
1958780,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,Resale flat prices based on registration date ...,88 years 6 months,True,Potential resale price anomaly
976769,2026-02,QUEENSTOWN,5 ROOM,92,DAWSON RD,19 TO 21,122.0,PREMIUM APARTMENT LOFT,2016,1700000.0,master_dataset.csv,88 years 6 months,True,Potential resale price anomaly
958277,2025-06,QUEENSTOWN,5 ROOM,92,DAWSON RD,22 TO 24,122.0,PREMIUM APARTMENT LOFT,2016,1658888.0,master_dataset.csv,88 years 6 months,True,Potential resale price anomaly